Vagrant.configure(2) do |config|
  config.vm.box = 'data-science-toolbox/dst'
  
  config.vm.network 'forwarded_port', guest: 8888, host: 8888
  config.vm.provision 'shell', path: './bootstrap.sh', privileged: false

  config.vm.synced_folder '.', '/home/vagrant/working_directory'
end
